<div>
  <h2>Final Grades</h2>
  <p>
    Your course grade is based on your grade on the midterm and final exams (35% each), your
    assignments score (20%), quizzes (5%), and takeaways (5%). As announced, the class did not
    reach 100% participation in the course evaluations. Had that happened, 4 people would have
    gone up half a letter grade, two others would have gone down half a letter grade, and the
    14 would not have been affected.
  </p>
  <p>
    Letter grades are based on your course average according to
    <a href="https://www.qc.cuny.edu/registrar/Documents/grading_guidelines.pdf">
    standard QC grading policy</a>.
  </p>
  <p>The distribution of grades for the class was:</p>
  <table><tr><th>A</th><th>B</th><th>C</th><th>D</th><th>F</th></tr>
    <tr><td>5</td><td>3</td><td>6</td><td>4</td><td>2</td></tr></table>
  <h2>Final Exam</h2>
  <p>
    There were 85 possible points on the exam, so each error deducted 100/85 from your score.
    However:
  </p>
  <ul>
    <li>There were so many binary-number questions on the first page that I took off only half
    a point for each error on that page.</li>
    <li>The smallest number of errors anyone made was 5, so I subtracted 4.5 from everyone’s
      number of errors.</li>
  </ul>
  <p>The class average on the exam was 80.1</p>
  <h2>Key to Assignment Items</h2>
  <table id='key-table'>
    <tr><th>Abbreviation</th><th>Due Date</th><th>Description</th></tr>
    <tr><th>A1</th><td>Aug 30</td><td>Initial Survey</td></tr>
    <tr><th>A2a</th><td>Sep 8</td><td>Basic Blink (Arduino setup and first sketch)</td></tr>
    <tr><th>A2b</th><td>Sep 8</td><td>Exploratory Blink</td></tr>
    <tr><th>A2c</th><td>Sep 8</td><td>Assignment 2 Questions</td></tr>
    <tr><th>A3</th><td>Sep 13</td><td>Mouse Maze: basic inputs-actions</td></tr>
    <tr><th>A4</th><td>Sep 20</td><td>“Interesting” NeoPixels</td></tr>
    <tr><th>A5</th><td>Sep 27</td><td>Online Questions</td></tr>
    <tr><th>A6</th><td>Oct 13</td><td>Mouse Maze: Design and Algorithm</td></tr>
    <tr><th>A8</th><td>Nov 10</td><td>Potentiometer to rotate colors</td></tr>
    <tr><th>A9</th><td>Dec 15</td><td>Last assignment: your choice</td></tr>
  </table>
</div>
