<div>
  <h2>Course Grades</h2>
  <p>
    As announced in class, we were unable to include a significant term project in the course,
    so 20% of the course grade had to be redistributed to other components of the course. I
    had proposed adding 10% to the weights of the midterm and final exams, but because the class
    had 100% participation in the course evaluations, just 5% was added to the weights of the
    midterm and final exams, 5% to takeaways and brief quizzes, and 5% to assignments.
  </p>
  <table>
    <tr>
      <th>Component</th><th>Syllabus Weight</th><th>Actual Weight</th>
    </tr>
    <tr>
      <th>Quizzes &amp; Takeaways</th><td>10%</td><td>15%</td>
    </tr>
    <tr>
      <th>Assignments</th><td>20%</td><td>25%</td>
    </tr>
    <tr>
      <th>Final Project</th><td>20%</td><td>—</td>
    </tr>
    <tr>
      <th>Midterm Exam</th><td>25%</td><td>30%</td>
    </tr>
    <tr>
      <th>Final Exam</th><td>25%</td><td>30%</td>
    </tr>
    <tr>
      <th></th><td>100%</td><td>100%</td>
    </tr>
  </table>
  <p>
    The points you got for each part of the course are shown under “Other Grades” above, followed
    by your course average and, finally, your letter grade for the course. Note that the conversion
    from your course average to your letter grade is a mechanical process specified by the College
    in which your average is rounded to an integer and assigned a letter grade as follows:
  </p>
  <table>
    <tr><th>Average</th><th>Grade</th></tr>
    <tr><td>97-100</td><td>A+</td></tr>
    <tr><td>93-96</td><td>A  </td></tr>
    <tr><td>90-92</td><td>A−</td></tr>
    <tr><td>87-89</td><td>B+</td></tr>
    <tr><td>83-86</td><td>B  </td></tr>
    <tr><td>80-82</td><td>B−</td></tr>
    <tr><td>77-79</td><td>C+</td></tr>
    <tr><td>73-76</td><td>C  </td></tr>
    <tr><td>70-72</td><td>C−</td></tr>
    <tr><td>67-69</td><td>D+</td></tr>
    <tr><td>60-66</td><td>D  </td></tr>
    <tr><td>0-59</td><td>F  </td></tr>
  </table>
  <p>
    For the class, there were 4 A’s; 9 B’s; 6 C’s; and one F. <em>The Registrar converts F’s to NC
    (no credit) for full-time first-semester freshmen.</em>
  </p>
  <h2>Final Exam Scoring</h2>
  <p>
    There were 51 chances to make mistakes on the exam. I scored it exactly the same way as the
    midterm.
  </p>
  <p>
    The class average was 77.4; the median was 80.5. There was one score in the 90‘s; 9 in the
    80‘s; 6 in the 70‘s; 3 in the 60‘s; and one below 60.
  </p>
  <h2>Midterm Exam Scoring</h2>
  <p>
    There were 44 chances to make mistakes on the exam. I counted all the mistakes you made
    (“Midterm Errors”), multiplied by two and subtracted
    from 100 to get your “Midterm Score.”
    Your “Midterm Rank” tells how you did compared to everyone else who took the exam: a rank of
    1 means you had the highest score; 20 means you had the lowest score.
  </p>
  <p>
    The class average was 81.3; the median was 84. There were 3 scores in the 90’s; 10 in the 80’s;
    5 in the 70’s; 1 in the 60’s; and 1 below 60.
  </p>
  <h2>Notes</h2>
  <p>
    These are your grades for the course to date. Report any errors to Dr. Vickery as soon as
    they are posted.
  </p>
</div>