/* include/config.h.  Generated by configure.  */
/* include/config.h.in.  Generated from configure.ac by autoheader.  */

/* 1234 = LIL_ENDIAN, 4321 = BIGENDIAN */
#define BYTEORDER 4321

/* Name of package */
#define PACKAGE "arcsim"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "arcsim"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "arcsim 0.3"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "arcsim"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.3"

/* The number of bytes in type int */
#define SIZEOF_INT 4

/* The number of bytes in type long */
#define SIZEOF_LONG 4

/* Version number of package */
#define VERSION "0.3"

/* whether byteorder is bigendian */
#define WORDS_BIGENDIAN 1
