
  This is, finally, to let you know that I received your Assignment 1
  for CS-81 and that your grade for the assignment is "ok" (full
  credit). Normally, I would give you some feedback on your answers
  for an assignment, but for this one there is not much I can say, so
  everyone who submitted the assignment is getting this same message.
  You did indeed visit academic, commercial, and entertainment sites
  and told me who the intended audiences were, and what you did or did
  not like about the sites you visited. Not much I can say about that!

  What might be interesting would be for you to revisit "your" sites
  at the end of the semester and see whether you reactions to them
  change at all as a result of taking CS-81.

  One thing I will note about many of the answers people gave is that
  what they generally liked about the sites had more to do with the
  content they offered rather than what they looked like or how easy
  they were to use, and what you generally thought could be improved
  had more to do with the appearance and ease of use than with the
  actual content.  We'll be working more on appearance and ease of use
  in this course than on content, so that works out well.

  Dr. Vickery

