<div>
  <h2>Notes</h2>
  <p>
    These are your grades for the course to date. Report any errors to Dr. Vickery as soon as
    they are posted.
  </p>
  <h3>Final Grades</h3>
  <p>
    I still need to double-check these, but they should be correct. The percentage that each part contributes to your course average is what was listed in the syllabus. The final project score is on a 10-point scale; everything else is on a 100-point scale.
  </p>
  <p>
    For the class as a whole, there were 3 A’s; 4 B’s; 3 C’s; and 1 D.
  </p>
  <h3>Final Exam</h3>
  <p>
    Although there were only 23 questions, there were 68 points because many questions had multiple parts. So each error reduced your score by 100/68. I subtracted your errors from 107.5 rather than 100. The class average was 79.5, and the median (middle score) was 84.5. When the average is so far away from the median like that, it means that the lowest scores were extremely low compared to the way most people did. There were 3 A’s; 4 B’s; 1 C; 1 D; and 2 F’s.
  </p>
  <h3>Final Project</h3>
  <p>
    There were eight criteria: getting a ”good” on everything would give 24 points; getting an “ok” on everything would give 16 points. I gave the groups an average of 18.2 points. I divided each group’s score by 21 and multiplied by 10 to give scores on a 10-point scale, but did not allow the score to go over 10.
  </p>
  <p>
    The scores you assigned were interesting: they were an average of 1 point (out of 24) higher than mine. Two groups rated themselves higher than the rest of the class did, and the other three rated themselves lower than the rest of the class did. The average difference overall was 0.8 points lower. I didn’t count the class ratings in determining the scores for the projects: that has to be my responsibility!
  </p>
  <h3>Laboratory 2</h3>
  <p>
    There are separate grades for the 2-bit counter, the 5-bit up-down counter, and the 5-bit up-down counter with switches and pushbutton inputs. The first and third parts are graded on the not-ok, ok, good scale; the second part was graded on a 10-point scale, with a grading report emailed to you. The soldering part was optional and was not scored.
  </p>
  <h3>Laboratory 1</h3>
  <p>
    There were three parts for Laboratory 1, each of which was graded on the ususal “not ok,”
    “ok,” “good” scale.
  </p>
  <h3>Midterm Grading</h3>
  <p>
    Most of the 41 questions counted 1 each. Exceptions were 1 (4); 2 (4.5); 16 (1.5);
    26(4); 27 (2). So it was possible to make as many as 51 errors. Your number of errors is given above in the Midterm Errors row. Each error counted 100/51 (= about 1.96 points). I subtracted
    the number of points lost from 106 instead of 100 because the least number of errors in the
    class was five. Your score is in the Midterm Score row, rounded to one decimal place. The
    precise value of your score, which used to be displaye here, is what will be used at the end of the term to compute your course grade.
  </p>
  <p>
    15 people took the exam. The Midterm Rank shows where you placed compared to everyone
    else: The highest score has a rank of 1, and the lowest score has a rank of 15. The median
    (middle) score has a rank of 8 (ranks 1-7 are above it, and ranks 9-15 are below it).
  </p>
  <p>
    The class average was 76.1, but the median was 81.5. There were 5 A’s; 3 B’s; 2 C’s;
    2 D’s; and 3 F’s.
  </p>
  <h3>BBC Information Video Assignment</h3>
  <p>
    Here is how I scored the TED-Ed assignment based on the BBC video on Information. You could get
    a maximum of 6 points, as shown below. I converted your number of points to a 10-point scale (6 points = 10; 5 points = 8.3; 4 points = 6.7), as shown in your grades above.
  </p>
  <table>
    <tr>
      <th style='text-align:left'>Item</th>
      <th style='text-align:left'>Max Points</th>
      <th style='text-align:left'>Points</th>
      <th style='text-align:left'>Criterion</th>
    </tr>

    <tr>
      <td rowspan="3">Multiple-choice Questions</td>
      <td rowspan="3">2</td>
      <td>2</td>
      <td>All correct within 1-2 attempts</td>
    </tr>
    <tr>
      <td>1</td>
      <td>More than one question required 3 or more attempts</td>
    </tr>
    <tr>
      <td>0</td>
      <td>One or more question not answered</td>
    </tr>

    <tr>
      <td rowspan="3">Maxwell’s Demon</td>
      <td rowspan="3">2</td>
      <td>2</td>
      <td>Explains relationship between information and physics</td>
    </tr>
    <tr>
      <td>1</td>
      <td>Describes Maxwell’s Demon, but not how it relates information to the physical world</td>
    </tr>
    <tr>
      <td>0</td>
      <td>Missing answer or does not answer the question</td>
    </tr>

    <tr>
      <td rowspan="3">Responsibility</td>
      <td rowspan="3">2</td>
      <td>2</td>
      <td>Provides at least one specific example of how information could be used responsibly</td>
    </tr>
    <tr>
      <td>1</td>
      <td>Vague or poorly-conceived response</td>
    </tr>
    <tr>
      <td>0</td>
      <td>Missing answer or does not answer the question</td>
    </tr>
    <tr>
      <th>Total</th>
      <td>6</td>
      <td colspan="2"></td>
    </tr>
  </table>
</div>