<fieldset>
  <legend><h3>Grade Computations</h3></legend>
  <p>
    Final Exam grades and Course Grades both involved complicated calculations, described here.
    Once the course grades were computed, the conversion to letter grades was done according to
    the standard Queens College grading policy:
  </p>
  <table>
    <tr>
      <td style='text-align:left; font-family:monospace;white-space:pre;'>A+ 97-100</td>
      <td style='text-align:left; font-family:monospace;white-space:pre;'>B+ 87-89</td>
      <td style='text-align:left; font-family:monospace;white-space:pre;'>C+ 77-79</td>
      <td style='text-align:left; font-family:monospace;white-space:pre;'>D+ 67-69</td></tr>
    <tr>
      <td style='text-align:left; font-family:monospace;white-space:pre;'>A  93-96</td>
      <td style='text-align:left; font-family:monospace;white-space:pre;'>B  83-86</td>
      <td style='text-align:left; font-family:monospace;white-space:pre;'>C  73-76</td>
      <td style='text-align:left; font-family:monospace;white-space:pre;'>D  60-66</td>
    </tr>
    <tr>
      <td style='text-align:left; font-family:monospace;white-space:pre;'>A- 90-92</td>
      <td style='text-align:left; font-family:monospace;white-space:pre;'>B- 80-82</td>
      <td style='text-align:left; font-family:monospace;white-space:pre;'>C- 70-72</td>
      <td style='text-align:left; font-family:monospace;white-space:pre;'>F   0-59</td>
    </tr>
  </table>
  <p>
    <strong>Note:</strong> If you check the calculations here (and I encourage you to do so), there
    may be rounding errors that will make your calculations appear to be different from what you
    see in your grading report. That’s because the fractional values shown in your report have been
    rounded to one decimal place. For example, an actual value of 2.45 would show as 2.5 in your
    report.
  </p>
  <h4>
    Final Exam Calculation
  </h4>
  <p>
    There were 45 possible points on the final exam, so each point was worth 100/45 = ~2.3%. But
    Question 13, which was worth 4 points, was impossible to answer as written so, for most people
    it was omitted, leaving 41 points for the exam (~2.4% per point). However, a few people saw the
    problem and wrote code that answered the question, as intended, correctly. They received full
    credit for the question, and their other errors counted ~2.3%.
  </p>
  <p>
    The class average for the final exam was 76.2 (no curve).
    There were 5 90’s, 4 80’s, 1 70’s, 3 60’s, and 4 scores below 60.
  </p>
  <h4>Course Average Calculation</h4>
  <p>
    If your final project was better than your exam average, it counted 10%
    of your course grade, and the exams counted 50%. But if your final project was worse than your
    exam average, it counted as one 10-point assignment, and the exams counted 60%. Although I made
    it clear in class that a final project was required of everyone, the syllabus said it would be
    required only for “advanced” students. So for the two people who did not submit a final project,
    it did not count as part of their Assignments grade (which turns out not to have mattered for
    their course grades).
  </p>
  <p>
    In all cases, Takeaways counted 5%, Quizzes counted 10%, and Assignments counted 25%.
  </p>
  <p>For the course, there were 7 A’s, 3 B’s, 4 C’s, and 3 D’s. Nobody failed.</p>
  </fieldset>
<div>
  <h3>Assignment Information</h3>
  <table>
    <tr><th>Abbreviation</th><th>Due Date</th><th style='text-align:center;'>Description</th></tr>
    <tr>
      <td style='text-align:left;padding-left:2em'>1A</td>
      <td style='text-align:left;'>February 7</td>
      <td style='text-align:left;'>Number Systems on TED-Ed</td>
    </tr>
    <tr>
      <td style='text-align:left;padding-left:2em'>1B</td>
      <td style='text-align:left;'>February 7</td>
      <td style='text-align:left;'>Number Systems Hand-in</td>
    </tr>
    <tr>
      <td style='text-align:left;padding-left:2em'>MM-I</td>
      <td style='text-align:left;'>February 16</td>
      <td style='text-align:left;'>Mouse Maze I on Perusall</td>
    </tr>
    <tr>
      <td style='text-align:left;padding-left:2em'>MM-II</td>
      <td style='text-align:left;'>February 28</td>
      <td style='text-align:left;'>Mouse Maze II Code</td>
    </tr>
    <tr>
      <td style='text-align:left;padding-left:2em'>Loopy</td>
      <td style='text-align:left;'>March 21</td>
      <td style='text-align:left;'>“Interesting” NeoPixel Effect</td>
    </tr>
    <tr>
      <td style='text-align:left;padding-left:2em'>Rotator</td>
      <td style='text-align:left;'>April 6</td>
      <td style='text-align:left;'>Potentiometer to change which NeoPixel is lighted</td>
    </tr>
    <tr>
     <td style='text-align:left;padding-left:2em'>3-bit Code V1</td>
      <td style='text-align:left;'>May 4</td>
      <td style='text-align:left;'>Type in and test Vickery’s 3-bit counter code on
        CircuitPlayground: “Version 1.”
      </td>
    </tr>
    <tr>
      <td style='text-align:left;padding-left:2em'>3-bit Code V2</td>
      <td style='text-align:left;'>May 9</td>
      <td style='text-align:left;'>Code and test 3-bit up counter that works with circuit on
        protoboard: “Version 2.” Individual assignment.
      </td>
    </tr>
    <tr>
      <td style='text-align:left;padding-left:2em'>3-bit Protoboard</td>
      <td style='text-align:left;'>May 9</td>
      <td style='text-align:left;'>Build 3-bit up counter circuit on protoboard (plug-in wires and
        alligator clips) for use with V2 code. Group assignment.
      </td>
    </tr>
    <tr>
      <td style='text-align:left;padding-left:2em'>3-bit Permaproto</td>
      <td style='text-align:left;'>May 11</td>
      <td style='text-align:left;'>Implement 3-bit up counter circuit on permaproto (soldered)
        circuit board. Test with V2 code. Group assignment.
      </td>
    </tr>
    <tr>
      <td style='text-align:left;padding-left:2em'>n-bit up/down</td>
      <td style='text-align:left;'>May 18</td>
      <td style='text-align:left;'>Implement n-bit up/down counter circuit on CircuitPlayground.
        Required of advanced students; optional (extra credit) for others. Individual assignment.
      </td>
    </tr>
    <tr>
      <td style='text-align:left;padding-left:2em'>Final Project</td>
      <td style='text-align:left;'>May 25</td>
      <td style='text-align:left;'>See <a
        href='https://drive.google.com/open?id=1zckGYUIPn1Xi38tIUB7hM_L6KmD8Dcdl7vl6v1H7VTg'>Final
        Project Assignment</a> for details.
      </td>
    </tr>
  </table>
</div>
