<div>
  <h2>Notes</h2>
  <h3>Course Grades</h3>
  <p>
    The class did not meet the 100% Evaluations challenge. Fourteen of you did complete the evaluations,
    but there were 18 people who completed the course (took the final). So the 20% of the course grade that
    was originally going to a “final project” was divided approximately equally across Assignments, the
    Midterm, and the Final exam, but not to the Quizzes and Takeaways. So the weights were:
    <table>
      <tr><td>Quizzes</td><td>5%</td></tr>
      <tr><td>Takeaways</td><td>5%</td></tr>
      <tr><td>Assignments</td><td>26%</td></tr>
      <tr><td>Midterm</td><td>32%</td></tr>
      <tr><td>Final</td><td>32%</td></tr>
    </table>
  </p>
  <p>
    Your course grade was rounded to the nearest integer, and converted to a letter grade using
    the College’s standard equivalents:
  </p>
    <table>
      <tr>
        <th>Course Grade</th>
        <td>&lt; 60</td>
        <td>60 - 66</td>
        <td>67 - 69</td>
        <td>70 - 72</td>
        <td>73 - 76</td>
        <td>77 - 79</td>
        <td>80 - 82</td>
        <td>83 - 86</td>
        <td>87 - 89</td>
        <td>90 - 92</td>
        <td>93 - 96</td>
        <td>97 - 100</td>
      </tr>
      <tr>
        <th>Letter Grade</th>
        <td>F</td>
        <td>D</td>
        <td>D+</td>
        <td>C-</td>
        <td>C</td>
        <td>C+</td>
        <td>B-</td>
        <td>B</td>
        <td>B+</td>
        <td>A-</td>
        <td>A</td>
        <td>A+</td>
      </tr>
    </table>
    <p>For the 18 people who took the final exam, the course grades were:</p>
  <table>
    <tr><td>A</td><td>5</td></tr>
    <tr><td>B</td><td>5</td></tr>
    <tr><td>C</td><td>6</td></tr>
    <tr><td>D</td><td>1</td></tr>
    <tr><td>F</td><td>1</td></tr>
  </table>
  <h3>Final Exam Scoring</h3>
  <p>
    There were 71 points on the exam, so each one counted 100/71 (approximately 1.408). As on the midterm,
    your grade is shown rounded, but the full fractional value was used to calculate your course grade.
  </p>
  <table>
    <tr><td>Average</td><td>76.88</td></tr>
    <tr><td>Median</td><td>73.94</td></tr>
    <tr><td>A</td><td>3</td></tr>
    <tr><td>B</td><td>4</td></tr>
    <tr><td>C</td><td>7</td></tr>
    <tr><td>D</td><td>3</td></tr>
    <tr><td>F</td><td>1</td></tr>
  </table>
  <h3>Midterm Scoring</h3>
  <p>There were 60 possible points, but 8 points for question 6 seemed like too much, so I
  reduced that one by 25%. Each mistake counted 1.5 points. Grades reported are rounded, but full
  fractional values are kept for computing course grade.</p>
  <table>
    <tr><td>Average</td><td>81.22</td></tr>
    <tr><td>Median</td><td>80.50</td></tr>
    <tr><td>A</td><td>6</td></tr>
    <tr><td>B</td><td>4</td></tr>
    <tr><td>C</td><td>7</td></tr>
    <tr><td>D</td><td>2</td></tr>
    <tr><td>F</td><td>0</td></tr>
  </table>

  <h3>
    Scoring for March 17 quiz.
  </h3>
  <p>
    There were 18 possible errors. In addition to your grade for the quiz, there is a score
    marked “3/18 errors” that tells how many errors you made. The class average was 6.3 errors.
    Fewer than three errors earned a “good” and 10 or more errors got “not ok.”
    Although this quiz counts no more than the others in the course, it gives you
    an idea of what sort of questions to expect on the midterm, and the above gives and idea of how
    it will be scored.
  </p>
  <hr/>
  <p>
    These are your grades for the course to date. Report any errors to Dr. Vickery as soon as
    they are posted.
  </p>
</div>
