<h2>Messages</h2>
<h3>Final Grades</h3>
<p>
  There were 50 possible answers on the final exam so each error counted 2 points. The class average
  was 75.3. The top score was 100; the bottom score was 28. There is <a
  href="https://docs.google.com/document/d/1G07N4KT0unR1jXl4yhL7XWGMaEPGcaC70_AD87sE_8g">a copy of
  the final exam with the correct answers</a> in the Quizzes section of the course website.
</p>
<p>
  Everyone elected to adjust the weights of the midterm and final, so that’s what “adjust” means in
  the Other Grades section.
</p>
<p>
  For the course, there were 8 A’s, 5 B’s, 4 C’s, no D’s, and two people failed.
</p>

<p>Best wishes for a great holiday/winter bread, and for the rest of your college career!</p>

<p><em>Dr. Vickery</em></p>
