<h2>Messages</h2>
<h3>
  Final Grades
</h3>
<p>
  For the final exam, each error counted 1.5 points. There was one perfect score on the exam:
  congratulations Hasanat! The
  class average was 73.9: 3 A’s; 2 B’s; 6 C’s; 1 D; 4 F’s.
  <a href="https://docs.google.com/document/d/1GApDy3k6N5a5LwjDgsoqPydeP6D5A1QHV110yDZevI0/edit?usp=sharing">
  The exam, with answers</a>, is on Google Drive, in the Quizzes folder.
</p>
<p>
  Jonathan had his exam grades adjusted by 5% because of his Hack && Tell. Samad and Weifeng did a
  joint Hack && Tell, but it was too late for them to do the “Tell” part, so their exam grades were
  adjusted by 2.5%.
</p>
<p>
  For the course, there were 6 A’s; 5 B’s; 3 C’s; 1 D; 1 F.
</p>
<p>Enjoy your summer!</p>
<p><em>Dr. Vickery</em></p>
